"""empty message

Revision ID: 713d6e1c5556
Revises: 
Create Date: 2020-11-10 10:39:23.401010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713d6e1c5556'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('hometown', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_bio'), 'artist', ['bio'], unique=False)
    op.create_index(op.f('ix_artist_hometown'), 'artist', ['hometown'], unique=False)
    op.create_index(op.f('ix_artist_name'), 'artist', ['name'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('eventVenue', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_dateTime'), 'event', ['dateTime'], unique=False)
    op.create_index(op.f('ix_event_eventVenue'), 'event', ['eventVenue'], unique=False)
    op.create_index(op.f('ix_event_name'), 'event', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_password_hash'), 'user', ['password_hash'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_location'), 'venue', ['location'], unique=False)
    op.create_index(op.f('ix_venue_name'), 'venue', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venue_name'), table_name='venue')
    op.drop_index(op.f('ix_venue_location'), table_name='venue')
    op.drop_table('venue')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_password_hash'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_event_name'), table_name='event')
    op.drop_index(op.f('ix_event_eventVenue'), table_name='event')
    op.drop_index(op.f('ix_event_dateTime'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_artist_name'), table_name='artist')
    op.drop_index(op.f('ix_artist_hometown'), table_name='artist')
    op.drop_index(op.f('ix_artist_bio'), table_name='artist')
    op.drop_table('artist')
    # ### end Alembic commands ###
